import type { PhaseConfig } from "@/types/game";

const pace = { canRequestHint: true, canSkipPhase: true, canRequestRecap: true, canFocusCharacter: true };
const adaptive = { stuckThresholdRounds: 3, boredThresholdRounds: 2, extraClueOnStuck: true, hiddenEventOnBored: true };

// 欢乐本：轻松娱乐，随机事件制造混乱（移植自 PRD 5.4）
export const COMEDY_PHASES: PhaseConfig[] = [
  {
    id: 0,
    name: "快速阅本阶段",
    description: "时间压缩，快速熟悉角色",
    estimatedMinutes: 6,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "READY_CONFIRMED" }, { type: "TIME", value: 360 }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "别太认真，我们是来找乐子的！快速看一眼你的角色。" } }],
    permissions: { publicChat: false, privateChat: false, clueInspection: false, voting: false },
    playerPaceControl: { ...pace, canRequestHint: false, canFocusCharacter: false },
    adaptiveConfig: adaptive,
  },
  {
    id: 1,
    name: "搞笑入戏阶段",
    description: "角色夸张自我介绍",
    estimatedMinutes: 8,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_INTRODUCED" }, { type: "TIME", value: 480 }],
    dmTriggers: [{ type: "PROMPT_CHARACTER", timing: "START", config: { order: "sequential", prompt: "用最夸张、最好笑的方式介绍你自己！" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: false, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 2,
    name: "自由混乱交流阶段",
    description: "随机事件卡触发，制造混乱",
    estimatedMinutes: 18,
    advanceConditions: [{ type: "TIME", value: 1080 }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "RANDOM_EVENT", timing: "MIDDLE", config: { kind: "comedy" } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: false, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 3,
    name: "线索收集",
    description: "轻量版，线索带娱乐性",
    estimatedMinutes: 12,
    advanceConditions: [{ type: "TIME", value: 720 }, { type: "PLAYER_ACTION", value: "CLUES_REVIEWED" }],
    dmTriggers: [{ type: "RELEASE_CLUE", timing: "START", config: { phase: 3, batchSize: 3 } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: true, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 4,
    name: "随机事件高潮",
    description: "DM 触发1~2个随机剧情转折",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "DM_DECISION" }, { type: "TIME", value: 600 }],
    dmTriggers: [{ type: "RANDOM_EVENT", timing: "START", config: { kind: "comedy" } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: true, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 5,
    name: "欢乐指凶阶段",
    description: "投票前每人说一句最搞笑的指控理由",
    estimatedMinutes: 8,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_STATED" }, { type: "TIME", value: 480 }],
    dmTriggers: [{ type: "PROMPT_CHARACTER", timing: "START", config: { order: "sequential", prompt: "用最离谱的理由指控一个人！" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: false },
    playerPaceControl: { ...pace, canSkipPhase: false },
    adaptiveConfig: adaptive,
  },
  {
    id: 6,
    name: "投票指凶",
    description: "提交投票",
    estimatedMinutes: 5,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_VOTED" }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "凭感觉投吧，反正都很可疑！" } }],
    permissions: { publicChat: false, privateChat: false, clueInspection: false, voting: true },
  },
  {
    id: 7,
    name: "揭秘",
    description: "含游戏中精彩发言回顾",
    estimatedMinutes: 8,
    advanceConditions: [],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "来，看看今天谁最离谱！" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: false },
  },
];
