import type { PhaseConfig } from "@/types/game";

const pace = { canRequestHint: false, canSkipPhase: true, canRequestRecap: true, canFocusCharacter: true };
const adaptive = { stuckThresholdRounds: 4, boredThresholdRounds: 3, extraClueOnStuck: false, hiddenEventOnBored: true };

// 情感本（哭哭本）：弱化推理，强化情感互动（移植自 PRD 5.3）
export const EMOTIONAL_PHASES: PhaseConfig[] = [
  {
    id: 0,
    name: "阅本阶段",
    description: "玩家阅读角色剧本，进入情感语境",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "READY_CONFIRMED" }, { type: "TIME", value: 600 }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "请静下心，走进这个关于人的故事。" } }],
    permissions: { publicChat: false, privateChat: false, clueInspection: false, voting: false },
    playerPaceControl: { ...pace, canFocusCharacter: false },
    adaptiveConfig: adaptive,
  },
  {
    id: 1,
    name: "情感入戏阶段",
    description: "角色介绍侧重情感背景，而非案情",
    estimatedMinutes: 12,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_INTRODUCED" }, { type: "TIME", value: 720 }],
    dmTriggers: [{ type: "PROMPT_CHARACTER", timing: "START", config: { order: "sequential", prompt: "请介绍你自己，多谈谈你的情感与牵挂。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: false, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 2,
    name: "自由交流阶段",
    description: "DM 适时推出情感触发事件",
    estimatedMinutes: 20,
    advanceConditions: [{ type: "TIME", value: 1200 }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "RANDOM_EVENT", timing: "MIDDLE", config: { kind: "emotional" } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: false, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 3,
    name: "深度对话阶段",
    description: "玩家与角色进行深度一对一私聊",
    estimatedMinutes: 20,
    advanceConditions: [{ type: "TIME", value: 1200 }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "现在，找一个你想深谈的人，单独聊聊吧。" } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: false, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 4,
    name: "情感高潮事件",
    description: "DM 触发核心戏剧冲突（关键真相揭示/情感决裂）",
    estimatedMinutes: 12,
    advanceConditions: [{ type: "DM_DECISION" }, { type: "TIME", value: 720 }],
    dmTriggers: [{ type: "RANDOM_EVENT", timing: "START", config: { kind: "emotional-climax" } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: true, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 5,
    name: "各角色表态阶段",
    description: "每个角色表达立场（不强制指凶，可为情感选择）",
    estimatedMinutes: 12,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_STATED" }, { type: "TIME", value: 720 }],
    dmTriggers: [{ type: "PROMPT_CHARACTER", timing: "START", config: { order: "sequential", prompt: "请表达你此刻的立场与心声。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: false },
    playerPaceControl: { ...pace, canSkipPhase: false },
    adaptiveConfig: adaptive,
  },
  {
    id: 6,
    name: "情感判定阶段",
    description: "侧重于你是否达成了情感目标（可选象征性表决）",
    estimatedMinutes: 8,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_VOTED" }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "如果愿意，请投出你心中那个最该被理解的人。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: false, voting: true },
    playerPaceControl: { ...pace, canSkipPhase: false, canFocusCharacter: false },
    adaptiveConfig: adaptive,
  },
  {
    id: 7,
    name: "复盘揭秘",
    description: "含情感线索梳理，真相揭示",
    estimatedMinutes: 10,
    advanceConditions: [],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "所有的心事，现在可以摊开了。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: false },
  },
];
