import type { PhaseConfig } from "@/types/game";

const fullPerms = { publicChat: true, privateChat: true, clueInspection: true, voting: false };
const pace = { canRequestHint: true, canSkipPhase: true, canRequestRecap: true, canFocusCharacter: true };
const adaptive = { stuckThresholdRounds: 3, boredThresholdRounds: 2, extraClueOnStuck: true, hiddenEventOnBored: true };

// 硬核本：信息量大，设中间推理节点 A/B（移植自 PRD 5.2）
export const HARDCORE_PHASES: PhaseConfig[] = [
  {
    id: 0,
    name: "阅本阶段",
    description: "时间更充裕，玩家深度阅读角色剧本",
    estimatedMinutes: 15,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "READY_CONFIRMED" }, { type: "TIME", value: 900 }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "信息量很大，请慢慢消化你们的剧本。" } }],
    permissions: { publicChat: false, privateChat: false, clueInspection: false, voting: false },
    playerPaceControl: { canRequestHint: false, canSkipPhase: true, canRequestRecap: true, canFocusCharacter: false },
    adaptiveConfig: adaptive,
  },
  {
    id: 1,
    name: "入戏自我介绍",
    description: "每个角色依次进行角色介绍",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_INTRODUCED" }, { type: "TIME", value: 600 }],
    dmTriggers: [{ type: "PROMPT_CHARACTER", timing: "START", config: { order: "sequential" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: false, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 2,
    name: "第一轮自由交流+搜证",
    description: "公开讨论并解锁第一批线索",
    estimatedMinutes: 20,
    advanceConditions: [{ type: "TIME", value: 1200 }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "RELEASE_CLUE", timing: "START", config: { phase: 2, batchSize: 3 } }],
    permissions: fullPerms,
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 3,
    name: "中间推理节点 A",
    description: "玩家提交阶段性推理，DM 给出方向提示（不透露真相）",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "REASONING_SUBMITTED" }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "请提交你目前对案情的判断，我会告诉你方向是否正确。" } }],
    permissions: fullPerms,
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 4,
    name: "第二轮深度搜证",
    description: "解锁更深层线索（需前置线索触发）",
    estimatedMinutes: 20,
    advanceConditions: [{ type: "TIME", value: 1200 }, { type: "PLAYER_ACTION", value: "CLUES_REVIEWED" }],
    dmTriggers: [{ type: "RELEASE_CLUE", timing: "START", config: { phase: 4, batchSize: 3 } }],
    permissions: fullPerms,
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 5,
    name: "中间推理节点 B",
    description: "再次提交推理，DM 给出进一步提示",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "REASONING_SUBMITTED" }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "再提交一次你的推理，我们快接近真相了。" } }],
    permissions: fullPerms,
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 6,
    name: "公开质询阶段",
    description: "多轮公开质询",
    estimatedMinutes: 15,
    advanceConditions: [{ type: "TIME", value: 900 }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "BROADCAST", timing: "STALL", config: { message: "几条证据链尚未闭合，建议重点核对时间线。" } }],
    permissions: fullPerms,
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 7,
    name: "最终陈词",
    description: "每个角色发表最终陈词",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_STATED" }, { type: "TIME", value: 600 }],
    dmTriggers: [{ type: "PROMPT_CHARACTER", timing: "START", config: { order: "sequential", prompt: "请发表最终陈词" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: false },
    playerPaceControl: { ...pace, canRequestHint: false, canSkipPhase: false, canFocusCharacter: false },
    adaptiveConfig: adaptive,
  },
  {
    id: 8,
    name: "投票指凶",
    description: "提交最终投票",
    estimatedMinutes: 5,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_VOTED" }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "请提交你认定的凶手。" } }],
    permissions: { publicChat: false, privateChat: false, clueInspection: false, voting: true },
  },
  {
    id: 9,
    name: "复盘揭秘",
    description: "真相揭示，胜负宣判",
    estimatedMinutes: 10,
    advanceConditions: [],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "揭开真相的时刻到了。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: false },
  },
];
