import type { PhaseConfig } from "@/types/game";

const pace = { canRequestHint: true, canSkipPhase: false, canRequestRecap: true, canFocusCharacter: true };
const adaptive = { stuckThresholdRounds: 3, boredThresholdRounds: 2, extraClueOnStuck: true, hiddenEventOnBored: true };

// 恐怖本：事件驱动，设生存/逃脱判定节点（移植自 PRD 5.5）
export const HORROR_PHASES: PhaseConfig[] = [
  {
    id: 0,
    name: "阅本阶段",
    description: "强调氛围渲染，进入恐怖语境",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "READY_CONFIRMED" }, { type: "TIME", value: 600 }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "深呼吸。接下来发生的一切，可能没有出口……" } }],
    permissions: { publicChat: false, privateChat: false, clueInspection: false, voting: false },
    playerPaceControl: { ...pace, canRequestHint: false, canFocusCharacter: false },
    adaptiveConfig: adaptive,
  },
  {
    id: 1,
    name: "入戏阶段",
    description: "DM 用环境描写营造氛围",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_INTRODUCED" }, { type: "TIME", value: 600 }],
    dmTriggers: [{ type: "PROMPT_CHARACTER", timing: "START", config: { order: "sequential" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: false, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 2,
    name: "自由探索阶段",
    description: "玩家探索不同场景，DM 触发恐怖事件",
    estimatedMinutes: 20,
    advanceConditions: [{ type: "TIME", value: 1200 }, { type: "DM_DECISION" }],
    dmTriggers: [
      { type: "RELEASE_CLUE", timing: "START", config: { phase: 2, batchSize: 2 } },
      { type: "RANDOM_EVENT", timing: "MIDDLE", config: { kind: "horror" } },
    ],
    permissions: { publicChat: true, privateChat: true, clueInspection: true, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 3,
    name: "生存判定节点 A",
    description: "DM 评估角色状态，可能触发濒危",
    estimatedMinutes: 8,
    advanceConditions: [{ type: "DM_DECISION" }, { type: "TIME", value: 480 }],
    dmTriggers: [{ type: "RANDOM_EVENT", timing: "START", config: { kind: "survival-check" } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: true, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 4,
    name: "继续探索+真相追踪",
    description: "解锁更深层线索，追踪威胁来源",
    estimatedMinutes: 18,
    advanceConditions: [{ type: "TIME", value: 1080 }, { type: "PLAYER_ACTION", value: "CLUES_REVIEWED" }],
    dmTriggers: [{ type: "RELEASE_CLUE", timing: "START", config: { phase: 4, batchSize: 2 } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: true, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 5,
    name: "逃脱/对抗判定节点",
    description: "找出元凶并对抗 / 找到逃脱路径，玩家做出关键抉择",
    estimatedMinutes: 12,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "DECISION_MADE" }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "只剩最后的机会了——对抗，还是逃跑？你必须选择。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: true },
    playerPaceControl: { ...pace, canRequestHint: true },
    adaptiveConfig: adaptive,
  },
  {
    id: 6,
    name: "结局揭示",
    description: "多结局分支：生存/牺牲/真相揭露",
    estimatedMinutes: 8,
    advanceConditions: [],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "你的选择，决定了今夜的结局……" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: false },
  },
  {
    id: 7,
    name: "复盘",
    description: "含恐怖事件触发逻辑揭示",
    estimatedMinutes: 8,
    advanceConditions: [],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "现在，揭开那些恐惧背后的真相。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: false },
  },
];
