import type { PhaseConfig } from "@/types/game";

const pace = { canRequestHint: true, canSkipPhase: true, canRequestRecap: true, canFocusCharacter: true };
const adaptive = { stuckThresholdRounds: 3, boredThresholdRounds: 2, extraClueOnStuck: true, hiddenEventOnBored: false };

// 还原本：还原历史真相，侧重时间线重建与证人陈述（移植自 PRD 5.6）
export const RESTORATION_PHASES: PhaseConfig[] = [
  {
    id: 0,
    name: "阅本阶段",
    description: "玩家阅读角色剧本，了解事件背景",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "READY_CONFIRMED" }, { type: "TIME", value: 600 }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "我们要做的，是把散落的碎片拼回历史的原貌。" } }],
    permissions: { publicChat: false, privateChat: false, clueInspection: false, voting: false },
    playerPaceControl: { ...pace, canRequestHint: false, canFocusCharacter: false },
    adaptiveConfig: adaptive,
  },
  {
    id: 1,
    name: "入戏阶段",
    description: "强调各角色与事件的关联",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_INTRODUCED" }, { type: "TIME", value: 600 }],
    dmTriggers: [{ type: "PROMPT_CHARACTER", timing: "START", config: { order: "sequential", prompt: "请说明你与这起事件的关联。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: false, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 2,
    name: "时间线梳理阶段",
    description: "DM 发布乱序事件碎片，玩家整理时间线",
    estimatedMinutes: 18,
    advanceConditions: [{ type: "TIME", value: 1080 }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "RELEASE_CLUE", timing: "START", config: { phase: 2, batchSize: 3, clueType: "TIMELINE" } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: true, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 3,
    name: "证人陈述轮",
    description: "每个角色依次陈述在特定时间点的行动",
    estimatedMinutes: 18,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_STATED" }, { type: "TIME", value: 1080 }],
    dmTriggers: [{ type: "PROMPT_CHARACTER", timing: "START", config: { order: "sequential", prompt: "请陈述你在关键时间点的确切行动。" } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: true, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 4,
    name: "对质与核实阶段",
    description: "发现陈述矛盾时组织对质，调取物证",
    estimatedMinutes: 15,
    advanceConditions: [{ type: "TIME", value: 900 }, { type: "DM_DECISION" }],
    dmTriggers: [{ type: "RELEASE_CLUE", timing: "MIDDLE", config: { phase: 4, batchSize: 2 } }],
    permissions: { publicChat: true, privateChat: true, clueInspection: true, voting: false },
    playerPaceControl: pace,
    adaptiveConfig: adaptive,
  },
  {
    id: 5,
    name: "时间线重建提交",
    description: "玩家提交完整时间线还原",
    estimatedMinutes: 10,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "TIMELINE_SUBMITTED" }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "请提交你还原的完整时间线，我将对照真相评分。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: false },
    playerPaceControl: { ...pace, canSkipPhase: false },
    adaptiveConfig: adaptive,
  },
  {
    id: 6,
    name: "真相确认+指认阶段",
    description: "确认时间线真相并指认关键人物",
    estimatedMinutes: 8,
    advanceConditions: [{ type: "PLAYER_ACTION", value: "ALL_VOTED" }],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "请指认在这段历史中负有关键责任的人。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: true },
  },
  {
    id: 7,
    name: "复盘",
    description: "展示完整时间线真相与各角色陈述对比",
    estimatedMinutes: 10,
    advanceConditions: [],
    dmTriggers: [{ type: "BROADCAST", timing: "START", config: { message: "现在，让历史的全貌呈现在你眼前。" } }],
    permissions: { publicChat: true, privateChat: false, clueInspection: true, voting: false },
  },
];
